cityofaustin/atd-data-publishing

bt_anonymize.py

Replaces identifying information in the Individual Address Files (IAF)
and the Individual Traffic Match Files (ITMF) generated by the BAT-433
Bluetooth sensors.

Added 'bt_anonymize.py' - anonymizes IAF and ITMF files.

---

data_helpers.py
detection_status.py
knack_api.py

The detector status updater script assigns a detection status to traffic signal records based on the status of the signal's detectors. When a signal's detection status changes, a detection status log table is also updated with the change in status.
A signal's detection status and the log of status changes funnel into two of our division's monthly performance meausres: # of signals with working detection, and # of signals at which detection was restored We're doing this as part of our effort to better track traffic detection issues and repairs.

Detector Status and Status Log Updater

---

open_data/sig_stat_pub.py
util/socratautil.py

This commit ensures that only fields that only fields in the destination dataset on socrata are included in the fields in the upload payload. The change applies to the signal status publication script, which hits the current signal status dataset (5zpr-dehc) and the historical status dataset (x62n-vjpq).

Reduce Signal Status Upload Fields to Dataset Keys

---

README.md
config/config.py
config/traffic_report_fields.py
data_tracker/traffic_reports.py
shell_scripts/pole_attachments.sh
shell_scripts/traffic_reports.sh
util/agolutil.py
util/datautil.py

This new script extracts, transforms, and loads into the Data Tracker "traffic reports" from this feed: http://www.ci.austin.tx.us/qact/qact_rss.cfm. The incidents will separately be published to the Open Data portal and incorporated into operations maps for the Traffic Management Center.

Traffic Report Feed ETL

---

.gitignore
config/config.py
config/esb_csr_template.xml
data_tracker/esb_xml_gen.py
data_tracker/esb_xml_send.py

This commit adds new scripts and configs to enable automated processing of service requests acitivites in the Data Tracker. The scripts poll the data tracker for activities carried out in response to service requests, and send those activities to the Enterprise Service Bus to be passed on to the CSR 311 system. Once deployed, these scripts will complete our integration with the 311 CSR system, allowing Arterial Management staff --including the Traffic Management Center-- to manage 311 service requests entirely in the Data Tracker.

ESB CSR Return Messaging

---

open_data/sig_stat_pub.py

This fixes a typo whereby the fieldname ":deleted" instead of "deleted" is explicitly added to the socrata payload fieldnames in the signal status script.

Signal Status: Fix ":deleted" Field Typo

---

config/config.py

This commit updates the data publishing config file to remove the 'fetch location' parameter' of signal cabinets. It causes signal cabinet data to be published with it's own location field, rather than that of it's related signal. This causes  the proper lat/lon info to downstream to ArcGIS Online and Socrata.

Cabinet Lat & Long Bug Fix

---

config/config.py
open_data/knack_data_pub.py
shell_scripts/signal_requests.sh

This commit provides config and shell scripts for publishign traffic and pedestrian signal requests to ArcGIS Online. Although we have been publishing signal request evaluations, we were not publishing any data at the signal request level.

Publish Signal Requests to ArcGIS Online

---

shell_scripts/kits_cctv_push.sh

This commit creates a shell script to fire off kits_cctv_push.py. The script was developed and deployed on the VM months ago, but was not tracked by the repo. That's fixed now.

KITS CCTV Push Shell Script

---

data_tracker/secondary_signals_updater.py
shell_scripts/kits_cctv_push.sh
shell_scripts/secondary_signals_updater.sh

This commit creates a shell script to fire off kits_cctv_push.py. The script was developed and deployed on the VM months ago, but was not tracked by the repo. That's fixed now.
This commit also updates the secondary_signals_updater shell script, which was missing the app_name paramater. It's been updated to point to the production system.

Shell Script Updates

---

open_data/sig_stat_pub.py
util/socratautil.py

This fix ensures that socrata location field is properly formatted on signal status payload by passing the correct lat and lon field names to the create_location_field function.

Create Socrata Location Fields Properly

---

util/socratautil.py

When we first started using the Socrata API, I was experiencing some weirdness where requests were routing to a different entity's data portal (I think it was City of Cincinnati). It was probably some  mistake on my end, but it also kinda seemed like a Socrata bug. The easiest solution at the time was to use Requests verify=false option, which was obviously not ideal.
After retesting without verify=false, it seems the re-routing issue is no longer an issue. So this commit removes verify=false from all of our Socrata requests and makes us sleep a lil better at night.

Verify Socrata Requests

---

data_tracker/device_status.py
shell_scripts/device_status_cameras.sh
shell_scripts/device_status_detectors.sh
shell_scripts/device_status_signals.sh
shell_scripts/device_status_travel_sensors.sh

Our scripting server (finally) has communications to the traffic signal network, so we're ready to deploy the nightly device status check scripts. To that end, this commit adds cross-platform support for pinging (the param flags are slightly different in windows vs linux/osx) and adds the shell scripts that will be deployed via cron.

Fixes for Device Status Check Deploy

---

data_tracker/location_updater.py
util/agolutil.py

This commit adds support for retrieving multiple features from an AGOL feature service by passing a search distance and units to the point_in_poly utility.
We've also updated the location_updater.py to use the functionality and parse the mutiple feature objects that this method returns. This allows us to properly identify locations which lie on the border of multiple council districts.

Handle Multiple Intersect Features on Point in Poly

---

data_tracker/detection_status_signals.py
data_tracker/device_status.py
data_tracker/esb_xml_send.py
data_tracker/location_updater.py
data_tracker/secondary_signals_updater.py
data_tracker/signal_pm_copier.py
data_tracker/signal_request_ranker.py
data_tracker/street_seg_updater.py
data_tracker/traffic_reports.py
open_data/dms_msg_pub.py

A minor tweak for the latest version of Knackpy: it's no longer necessary to pass a record id key to the update_record method. The method defaults to the ID key 'id', which is what we were passing in every instance.

Upgrade to Knackpy 0.0.5

---

config/knack/config.py
data_tracker/device_status_log.py
shell_scripts/device_status_log_cameras.sh
shell_scripts/device_status_log_signals.sh
shell_scripts/device_status_log_travel_sensors.sh

This script generates network devicce communication statistics and uploads them to the data tracker. It does so by downloading device data and grouping/counting devices by their IP_COMM_STATUS. These stats are used to generate daily reports of the # of field devices which are online/offline/not comm enabled.

Device Communication Status Logging

---

data_tracker/esb_xml_gen.py
data_tracker/esb_xml_send.py

Adds functionality to ensure ESB messages are delibered in chronological order. This is accomplished by adding an incremental record ID prefix to the message filename, and sorting messages by this ID when sending.
With this fix we're also updating Knack after each message is successfully sent, rather than sending all messages then updating all knack records. This ensures that if communication is interrupted during message send the Data Tracker and CSR will stay in sync.

Enforce Chronological ESB Message Send

---

config/knack/config.py
data_tracker/device_status_log.py
shell_scripts/device_status_log_gridsmart.sh

Update config and script logic to handle device records with varying status fields, rather than assume every device uses 'TURNED_ON.'
Plus shell scripts :)

Log GRIDSMART Device Status

---

open_data/radar_count_pub.py

Update the SQL query to just join logic to retrieve current detector naems when -replace flag is used to replace all radar data at socrata endpoint.

Update SQL Query for Radar Data Replace

---

build.py
build.sh
config.py
deploy.sh
tdp.logrotate

Use the current build path (os.getwcd()) when generating the logrotate config. Otherwise we don't where the log files are, so they don't rotate.

Use Build Path in Logrotate Config

---

transportation-data-publishing/data_tracker/street_seg_updater.py
transportation-data-publishing/util/agolutil.py

Street segment updater was failing today because we weren't providing a token with our request. Apparently a token is required now. Not sure why. It's a public dataset. Hrmph. Probably a best practice going forward to include a token with any AGOL method.

Use Token to Query Street Segments

---

transportation-data-publishing/data_tracker/traffic_reports.py

Sometimes we get mysterious exceptions with the traffic report data parsing. We don't really understand the source of the RSS feed we're parsing and don't have access to the source data for torubleshooting. So I added a bit more logging based on an infrequent IndexError. Maybe this will help.

Better Traffic Report Logging

---

transportation-data-publishing/data_tracker/backup.py

Knack strings can contain unicode characters, and to this point we've not made any attempt to handle unicode. The issue finally came up with a bunk apostrpohe made it's way into one of..my change log entries caused the backup script to fail.
We should be handling this in knackpy's to_csv() method. For now we're encoding the entire dicionary if we catch a UnicodeError.

Handle Unicode

---

transportation-data-publishing/open_data/knack_data_pub.py
transportation-data-publishing/util/datautil.py

Running into occasional encoding issues because our scripts try to print() record data without handling the encoding. We're not printing record data anymore.

Stop Printing Unencoded Stuff

---

transportation-data-publishing/data_tracker/kits_cctv_push.py

This script was failing because **someone** left a pdb.set_trace(0) before the INSERT statement.
Added traceback logging as well.

Remove a Debugging Trace

---

transportation-data-publishing/data_tracker/markings_agol.py

ArcGIS Online does not like empty strings in date fields (it converts them to 1/1/1899, so we're removing empty strings from the payload before uploading.

Remove Empty Strings from Payload

---

transportation-data-publishing/config/knack/config.py

Add another reference object to the markings materials config so that field names/data are grabbed from the inventory_items object.

Update Markings Materials Config

---

transportation-data-publishing/config/postgrest/config.py
transportation-data-publishing/open_data/pgrest_data_pub.py

This commit enables publishing of dockless trip data from our public postgrest endpoint at transportation-data.austintexas.io to the Open Data Portal (socrata).
- add config for `dockless_trips` to existing postgrest > socrata publishing script (`pgrest_data_pub.py`)
- tweak publishing config and remove some hard-coded values

dockless trip pub

---

transportation-data-publishing/open_data/pgrest_data_pub.py

Turns out we were not properly handling/formatting the  `--last_run_date` param in postgrest to socrata publisher. The param is submitted via client arg as a unix timetstamp, converted to an ISO string, and then used as the basis of a query to postgrest for the most recently modified records.
We were using `arrow` for this, and it's default format string was not ISO8601, and it was causing postgrest to only parse the date, and not the time, when handling the query.
We're now using built-in `datetime` methods (yay), and we're making sure the timestamp in the query string is ISO8601.

Use pgrest-friendly data format

---

requirements.txt
transportation-data-publishing/open_data/sig_stat_pub.py

Fixes #230 
The socratautil was throwing a `ValueError` when trying to convert datetimes for this script, with source data coming from KITS. Turns out we this script is now passing in ISO datestrings instead of mills. I tried really hard to understand why we're no longer passing in millisecond timestamps. I thought it might be an issue related to a new release of Arrow, but rolling back to `0.12.0` and `0.10.0` did not fix the issue. I also consider a KITS DB schema change, but we're receiving `datetime` objects like always. So it remains a mystery. To fix this, we've added support for a new `source=kits` parameter in the `Soda` class, which will handle the input dates as ISO strings.

Signal Status: Support New "kits" Socratautil Source

---

transportation-data-publishing/config/knack/config.py
transportation-data-publishing/data_tracker/markings_agol.py

Fixes [this issue](https://github.com/cityofaustin/atd-data-tech/issues/343) in `atd-data-tech`.
Updates the publisher config to point to the new app, and also now fetches markings job geometries from the markings work orders. This reduces our AGOL calls by 50%.

Point Markings Work Order Publisher to New App

---

transportation-data-publishing/config/knack/config.py

A shoddy find & replace inserted unintentional changes to object names the `backup` config. This restores the previous object names.

Revert Backup Config Entries

---

transportation-data-publishing/data_tracker/device_status.py

We were calling open_socket() by using `port=wxyz`, however the method used a positional `port` parameter. This switches the arg to a named parameter with a default value of 8902.

Fix Named Arg in open_socket() Method

---

transportation-data-publishing/config/knack/config.py
transportation-data-publishing/data_tracker/markings_agol.py
transportation-data-publishing/data_tracker/signs_agol.py
transportation-data-publishing/open_data/knack_data_pub.py

This script publishes signs work orders from our asset management application (Knack) to a [feature service](https://austin.maps.arcgis.com/home/item.html?id=93e29b23c39b4110ab0bbefde79b4063) on ArcGIS Online.

Publish Signs Work Orders to AGOL

---

transportation-data-publishing/config/esb/esb_csr_template_signals.xml
transportation-data-publishing/data_tracker/esb_xml_gen.py
transportation-data-publishing/data_tracker/esb_xml_send.py

Fixes [#81](https://github.com/cityofaustin/atd-knack-data-tracker/issues/81).
Wait 10 seconds between XML message publications to the ESB.
We're hoping this causes the activities to be processed by CSR chronologically.

Add Delay Between Outbound Messages to ESB

---

transportation-data-publishing/bcycle/bcycle_trip_pub.py

We added a `source` param to ` socratautil.Soda` as part of our upgrades for the new Socrata date validations. This PR sets the B-Cycle source to `bcycle` to ensure dates are processed correctly. It's been tested and is ready to deploy.

Update B-Cycle Pub for New Socrata `Source` Param

---

transportation-data-publishing/open_data/radar_count_pub.py

Fixes #266. The radar count publisher has been failing because, due to Socrata's announced API changes, date fields are returned as strings instead of unix integers. This patch handles those dateststrings so that they can be evaluated against the most recent data available in the KITS DB.

Fix Radar Type Mismatch
