cityofaustin/atd-data-publishing

- config/config.py
- shell_scripts/cabinets.sh
- shell_scripts/dms.sh
- shell_scripts/hazard_flashers.sh
Updated config to allow for new datasets to be published to Socrata and arcGIS online.
> Added Cabinets, DMS, and Hazard Flashers to ETL Workflow

- open_data/dms_msg_pub.py
- shell_scripts/dms_msg_pub.sh
- util/datautil.py
This queries the KITS database for the messages and time stamp of DMS signs. Then places those messages in the Knack database.
> KITS DMS Messages to Knack Database

- open_data/sig_stat_pub.py
- util/socratautil.py
Our scripting server (finally) has communications to the traffic signal network, so we're ready to deploy the nightly device status check scripts. To that end, this commit adds cross-platform support for pinging (the param flags are slightly different in windows vs linux/osx) and adds the shell scripts that will be deployed via cron.
> Fixes for Device Status Check Deploy

- data_tracker/kits_cctv_push.py
With this commit we add support for disabling CCTV image publication for specified cameras. A "DISABLE_IMAGE_PUBLISH" field in the Data Tracker is translated to a SkipDownload field in the KITS database, which causes the image publication service to ignore the camera.
> Handle Disable CCTV Image Publish Flag

- data_tracker/detection_status.py
The script -- signal_detection_status -- assigns a detection status value (OK, BROKEN, NO DETECTION) to traffic signal records in the Data Tracker. It does so by iterating through individual detector records and grouping them by their signal.
This script will allow us to report on overall detection health across the traffic signal network, which happens to be a key performance indicator.
> Signal Detection Detection Status

- data_tracker/esb_xml_gen.py
We publish service request updates to the 311/CSR system via the CTM-managed Enterprise Service Bus.
The ESB does not except any unencoded special characters in its messaging, so we had previously removed from our messaging any non-ASCII characters. As it turns out this wasn't enough, we also need to remove characters that are invalid to XML, &, <, >, etc. So we're doing that now by explicitly replacing them when building message content.
> Parse Invalid XML Characters for ESB Message Transmit

- data_tracker/kits_cctv_push.py
Fixes an issue where we were trying and failing to write true/false strings to BIT fieldtypes in the KITS (MSSQL) database.
This resolves that issue and allows us to re-deploy the Data Tracker > CCTV synchronization script.
> Convert Booleans to Bits when Writing to SQL

- util/kitsutil.py
This commit adds a touch of error handling when attempting to connect to the KITS MSSQL database via the PYMSSQL module. It adds a dedicated get_conn() method to the KITS util scripts, which includes a try/except wrapper to handle connection failures. The method will attempt to reconnect to the DB on failure, update a specified number of tries.
Although I've been unable to identify why KITS DB connections sometimes fail, this should drastically reduce the number connection of errors we see. Tests showed that a second try is typically all that is required to successfully connect.
> Handle MSSQL Connection Errors and Retry

- open_data/dms_msg_pub.py
Handles parsing of two recently found formatting brackets from DMS Messages
> DMS Message Parsing

- data_tracker/device_status.py
Use Python mulit-threading (via multiprocessing.dummy) to speed up device pinging. Also assign a "NO COMMUNICATION" status to devices that do not have an IP address.
> Multithreaded Device Pinging and Introduce "NO COMMUNICATION" Status

- util/socratautil.py
Add support for SoQL query parameters to be passed as soql argument to Soda class. Also merge private/public dataset methods and add some docstrings.
Change is backwards compatible, no scripts need to me modified at this time.
> Enhanced Query Support and Soda Class Refactor

- open_data/knack_data_pub.py
Add better logging to handle failed AGOL addFeatures.
> Debugging AGOL Pub Error

- open_data/radar_count_pub.py
Fix time formatting issues that were preventing proper checking for new data.
> Radar Count Pub Updates

- config/knack/config.py
- shell_scripts/work_orders.sh
- util/socratautil.py
Add config and shell script for publishing of traffic signal work orders to open data portal. Add an auth attribute to socratautil's soda class to simplify auth workflows.
> Traffic Signal Work Order Publishing

- config.py
- transportation-data-publishing/traffic_study/traffic_study_locations.py
Populate location field properly by identifying the correct lat/lon field names when calling socratautil.create_location_fields().
> Fix Location Fields

- transportation-data-publishing/open_data/knack_data_pub.py
- transportation-data-publishing/util/agolutil.py
Fix AGOL publish handling so that an exception is raised when features fail to add.
> Handle AGOL Publish Failures

- requirements.txt
- transportation-data-publishing/config/knack/config.py
- transportation-data-publishing/data_tracker/task_orders.py
This script scrapes the Controller's internal website for ATD's task orders. It compares these task orders with those that already exist in the Data Tracker and uploads any new task orders accordingly. It adds another python package dependency: beautiful soup.
> Task Order Processor

- transportation-data-publishing/config/postgrest/config.py
- transportation-data-publishing/config/traffic_report/meta.py
- transportation-data-publishing/data_tracker/traffic_reports.py
- transportation-data-publishing/open_data/pgrest_data_pub.py
- transportation-data-publishing/util/pgrestutil.py
- transportation-data-publishing/util/socratautil.py
Apply some very stupid fixes to the traffic reports pusher and also introduce a data publisher for postgrest. Currently only supports publishing to Socrata. But, yay.
> Traffic Reports + Postgrest Data Pub

- transportation-data-publishing/data_tracker/backup.py
Hi, John,
I added a function in backup.py to backup all objects in an app except things that we don't want to backup.
> added a function in backup.py to backup all objects in a app

- transportation-data-publishing/data_tracker/kits_cctv_push.py
1. Moved all static variables to a seperated dictionary under config/kits/config, the name of the ditionary is KITS_CONFIG
2. Replaced all kits_cred with  KITS_CREDENTIALS since they are same unless we have any special concerns
3. Changed the return argument from a ditionary which contains the number of "new", "change", "no_change", "delete" dictionary to only the number of changed records to keep the consistency with other script
> Kits cctv fix joey

- transportation-data-publishing/data_tracker/tcp_business_days.py
reference obj as config["obj"]
> Fix tcp business day joey

- transportation-data-publishing/data_tracker/street_seg_updater.py
With this commit the street segment updater script compares the values of the ArcGIS Online (AGOL) segment data against the existing segment data in the Data Tracker, and only updates Data Tracker records if the two data sources are different. Prior to this commit, we were assuming any segment that had been modified in data tracker would need to be updated form AGOL, because the Data Tracker only allows the creation of new segments.
By comparing the contents of the two sources, we could now initiate a total refresh of the Data Tracker segment data my updating the modifed data of all segments. This would result in the script checking AGOL for new data, but only updating changed records in the data tracker.
> Only Update Modified Segments

- transportation-data-publishing/config/knack/config.py
- transportation-data-publishing/data_tracker/signal_pms_fulcrum.py
1. Fixed signal_modified time not update bug in replace method by calling the update_signals_modified_time function inside the replace function.
2. Fixed duplicate signal_id column warning by deleting one of the signal_id column inside the map_knack_id_signal_id function
3. added printing function to monitor the inserting and updating progress for testing.
> multiple bug fixes, please check description

- transportation-data-publishing/data_tracker/signal_pms_fulcrum.py
bug fix: catch the case that deleting ids to avoid duplicates while id is not in payload (new pms)
> Postgre knack

- transportation-data-publishing/data_tracker/signal_pms_fulcrum.py
Modified the get_postgre_record function to only get the most recent record from postgreSQL if two records have the same fulcrum_id.
> Fix fulcrum technician bug

- transportation-data-publishing/config/knack/config.py
See also: https://github.com/cityofaustin/atd-data-publishing/pull/252
> Restore Correct Object Reference in Street Seg Config

- transportation-data-publishing/open_data/knack_data_pub.py
Fixes #262
This PR updates configs to point our scripts to our postgREST load balancer instead of `transportation-data.austintexas.io`
> [Prod Deploy] Update Knack and PostgREST Configs to Point to PostgREST Load Balanacer

- transportation-data-publishing/data_tracker/task_orders.py
In the past, we were not updating task orders in the data tracker after they were created. This PR  detects changes in task orders from the finance system and udpates changed task orders. Most importantly, this ensures the task orders' `ACTIVE` status is kept up to date.
> Detect Changes Between Old/New Task Orders

- transportation-data-publishing/data_tracker/markings_agol.py
Fixes [#1407](https://github.com/cityofaustin/atd-data-tech/issues/1407)
> Chunk AGOL Record Deletes

- transportation-data-publishing/data_tracker/signs_agol.py
Fixes [1409](https://github.com/cityofaustin/atd-data-tech/issues/1409)
> Sanitize HTML From Paragraph Text

- transportation-data-publishing/config/knack/config.py
Closes part of [cityofaustin/atd-data-tech#1241](https://github.com/cityofaustin/atd-data-tech/issues/1241)
Adds mmc_activities object to config.py
Requesting Mike's and John's review, copying Mateo and Sergio as a heads up!
> added mmc_activities to config

- requirements.txt
This PR sets explicit versions in `requirements.txt` for `atd-data-util` (v0.1.0) and `atd-socrata-util` (v0.0.10) for testing updates to these tools.
> Update requirements versions
